import type { Label } from '../../../primitives/drag-label/types';

/** 34 个省级行政区。targetFeatureId 对应 map.json 的 feature.properties.id(行政区划代码)。 */
export const LABELS: Label[] = [
  { id: 'beijing', text: '北京市', targetFeatureId: '110000' },
  { id: 'tianjin', text: '天津市', targetFeatureId: '120000' },
  { id: 'hebei', text: '河北省', targetFeatureId: '130000' },
  { id: 'shanxi', text: '山西省', targetFeatureId: '140000' },
  { id: 'neimenggu', text: '内蒙古', targetFeatureId: '150000' },
  { id: 'liaoning', text: '辽宁省', targetFeatureId: '210000' },
  { id: 'jilin', text: '吉林省', targetFeatureId: '220000' },
  { id: 'heilongjiang', text: '黑龙江', targetFeatureId: '230000' },
  { id: 'shanghai', text: '上海市', targetFeatureId: '310000' },
  { id: 'jiangsu', text: '江苏省', targetFeatureId: '320000' },
  { id: 'zhejiang', text: '浙江省', targetFeatureId: '330000' },
  { id: 'anhui', text: '安徽省', targetFeatureId: '340000' },
  { id: 'fujian', text: '福建省', targetFeatureId: '350000' },
  { id: 'jiangxi', text: '江西省', targetFeatureId: '360000' },
  { id: 'shandong', text: '山东省', targetFeatureId: '370000' },
  { id: 'henan', text: '河南省', targetFeatureId: '410000' },
  { id: 'hubei', text: '湖北省', targetFeatureId: '420000' },
  { id: 'hunan', text: '湖南省', targetFeatureId: '430000' },
  { id: 'guangdong', text: '广东省', targetFeatureId: '440000' },
  { id: 'guangxi', text: '广西', targetFeatureId: '450000' },
  { id: 'hainan', text: '海南省', targetFeatureId: '460000' },
  { id: 'chongqing', text: '重庆市', targetFeatureId: '500000' },
  { id: 'sichuan', text: '四川省', targetFeatureId: '510000' },
  { id: 'guizhou', text: '贵州省', targetFeatureId: '520000' },
  { id: 'yunnan', text: '云南省', targetFeatureId: '530000' },
  { id: 'xizang', text: '西藏', targetFeatureId: '540000' },
  { id: 'shaanxi', text: '陕西省', targetFeatureId: '610000' },
  { id: 'gansu', text: '甘肃省', targetFeatureId: '620000' },
  { id: 'qinghai', text: '青海省', targetFeatureId: '630000' },
  { id: 'ningxia', text: '宁夏', targetFeatureId: '640000' },
  { id: 'xinjiang', text: '新疆', targetFeatureId: '650000' },
  { id: 'taiwan', text: '台湾省', targetFeatureId: '710000' },
  { id: 'xianggang', text: '香港', targetFeatureId: '810000' },
  { id: 'aomen', text: '澳门', targetFeatureId: '820000' },
];
